### ISSUE TITLE
make failed on MSYS2 

### ISSUE THREAD

**Issue by ChisAdrian** [maharmstone/tdscpp#1]
after 
$ cmake ..
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: .....
$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by maharmstone** [comment]
I've not tested against MSYS2, but it looks like its version of CMake is broken. Try Cygwin, WSL, or MSVC.
