### ISSUE TITLE
Unable to Build - nlohmann_jsonConfig

### ISSUE THREAD

**Issue by naushadck** [maharmstone/tdscpp#2]
Hello, 

Getting the following error while building using cmake under windows. 

Could not find a package configuration file provided by "nlohmann_json"
  with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

How to fix this. Any support.

**Comment by maharmstone** [comment]
You need to install https://github.com/nlohmann/json. Apologies, the README doesn't make it clear that this is a dependency.

On Windows, the easiest way might be to use vcpkg, which will pull in nlohmann-json automatically.

**Comment by naushadck** [comment]
Thank you for your kind support. 
I am not using vcpkg. i am using cmake. Found it is simple and faster.

I like to include this nlohmann/json project cloned folder within the tdscpp source build folder. 

Can you please guide me on how to include this way and the find_package() command take the necessary files from this. 
Thanks

**Comment by maharmstone** [comment]
Google will be able to help you to direct find_package() to look in particular places.
I do strongly recommend that you look into a package manager though, it will take care of things like this for you. Like I said, vcpkg is the best one for Windows, and it uses CMake.

**Comment by naushadck** [comment]
Thank you. I used the vcpkg to install. However it is failed.  Error is given below. 

error: building tdscpp:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle tdscpp:x64-windows: 26 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tdscpp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tdscpp]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FProgram%20Files%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
