### ISSUE TITLE
Error with call to gettid() undeclared

### ISSUE THREAD

**Issue by devisbal** [maharmstone/tdscpp#3]
Hi:

Trying to install on RedHat 8.10 either with vcpkg or doing cmake got error on gettid() [undeclared].

FAILED: CMakeFiles/tdscpp.dir/src/tdscpp.cpp.o
/usr/bin/clang++ -DTDSCPP_EXPORT -I/opt/vcpkg/buildtrees/tdscpp/x64-linux-dbg -I/opt/vcpkg/buildtrees/tdscpp/src/20240707-7db950aace.clean/src -isystem /opt/vcpkg/installed/x64-linux/include -pthread  -fPIC -g -std=gnu++23 -fvisibility=hidden -Wall -Werror=cast-function-type -Wno-expansion-to-defined -Wunused-parameter -Wtype-limits -Wextra -Wconversion -fstrict-aliasing -MD -MT CMakeFiles/tdscpp.dir/src/tdscpp.cpp.o -MF CMakeFiles/tdscpp.dir/src/tdscpp.cpp.o.d -o CMakeFiles/tdscpp.dir/src/tdscpp.cpp.o -c /opt/vcpkg/buildtrees/tdscpp/src/20240707-7db950aace.clean/src/tdscpp.cpp
/opt/vcpkg/buildtrees/tdscpp/src/20240707-7db950aace.clean/src/tdscpp.cpp:2064:49: error: use of **undeclared identifier 'gettid'**
 2064 |     auto fn = format("/proc/self/task/{}/comm", gettid());
      |        

=
[root@fenix build]# make
[  5%] Building CXX object CMakeFiles/tdscpp.dir/src/tdscpp.cpp.o
/root/tdscpp/src/tdscpp.cpp: In function ‘void name_thread(std::string_view)’:
/root/tdscpp/src/tdscpp.cpp:2064:49: error: ‘gettid’ was not declared in this scope; did you mean ‘getuid’?
 2064 |     auto fn = format("/proc/self/task/{}/comm", gettid());
      |                                                 ^~~~~~
      |                                                 getuid

What I have done and the test passed was to add to tdscpp.cpp:
#define gettid() syscall(SYS_gettid)

Maybe you have other solution

**Comment by maharmstone** [comment]
This looks like the way to do it.

`gettid` was added to glibc 2.30 (released 2019), but RHEL 8.10 ships with glibc 2.28 (released 2018). Oddly it comes with a modern-ish version of Clang but an ancient version of glibc.
The proper solution is probably to upgrade to RHEL 9 when you can.
