### ISSUE TITLE
Test colltest have server user password predefined

### ISSUE THREAD

**Issue by devisbal** [maharmstone/tdscpp#4]
Hi:

While running colltest, I got an error.
Found that this colltest.cpp have predefined:
tds::tds tds("mssql", "sa", "Password1$");

instead of what do you have the tdscpp-test.cpp
that ask for server, user, password.

**Comment by maharmstone** [comment]
Thanks - I've changed it so it works similarly to tdscpp-test. It's not a very useful program, but it certainly shouldn't have the credentials hard-coded.
