### ISSUE TITLE
Not an issue, but a question about UTF-16

### ISSUE THREAD

**Issue by devisbal** [maharmstone/tdscpp#5]
All this library assume that MS SQL is UTF16 for all, but there is MS-SQL based only on UTF-8
That means that a lot of conversion is done internally without need.

==
/* MSSQL stores column names at UTF-16, but you can use tds::utf16_to_utf8 to fix this. */
BCP - If you pass normal strings rather than UTF-16, they will get converted for you.
==

Not so sure, but can there be a version for all in UTF-8?

BR

**Comment by maharmstone** [comment]
Unless things have changed very recently, like the comment says all column names, table names etc. are stored as UTF-16.

Queries return `tds::value`s, which can be cast to std::u8string (UTF-8), std::string (also UTF-8), or std::u16string (UTF-16). If the underlying type is an NVARCHAR, casting it to a std::u16string won't do any extra work. Similarly casting a VARCHAR with a UTF-8 collation to a std::string or std::u16string won't do any extra work.

If you pass a std::string in to BCP, it will assume that it's UTF-8, and will either pass it in as is (for UTF-8 VARCHARs), convert to another codepage (for other VARCHARs), or convert it to UTF-16 (for NVARCHARs).

There shouldn't be any needless conversions at any point.
