### ISSUE TITLE
Error: call to consteval function 'tds::checker<char, 0>::checker' is not a constant expression

### ISSUE THREAD

**Issue by devisbal** [maharmstone/tdscpp#6]
It's possible to use this code, and how?

char cmdc[1000];
buff_n have the column names
buff_o have the values
sprintf(cmdc, "INSERT INTO laffic.bplm6 (%s) VALUES(%s)", buff_n, buff_o);
conn.run(cmdc);

Severity	Code	Description	Project	File	Line	Suppression State	Details
**Error		call to consteval function 'tds::checker<char, 0>::checker' is not a constant expression**
 1487 |     conn.run(cmdc);
      |              ^	consumer2db	\Linux\consumer2db\funcrtn-laffic.cpp	1487

**Comment by maharmstone** [comment]
Oh, I thought this was in the README, it's not. I've added a bit at the bottom about compile-time checks.

**Comment by devisbal** [comment]
I think this need to be changed:
tds.run(tds::no_check{q}, value);
for  
conn.run(tds::no_check{q}, value);

And this line gives me an error:
static void do_insert(tds::tds& tds, const std::string& column_name, std::string_view value) {
function definition is not allowed here

I made it work just for example:
std::vector<char> cmd(500);
Thnks.
{
    sprintf(cmd.data(), "UPDATE laffic.ficc1 SET %s = %d WHERE nroreg = %d","cod",4,4);
    conn.run(tds::no_check{cmd.data()});
}

Also work for INSERT.
char q[100];
{
    sprintf(q, "INSERT INTO laffic.ficc1(%s) VALUES(%d)", "cod", 100);
    conn.run(tds::no_check{ q });
}

Question:
How to check there was an error during the execution?
I do a test trying to update a non-existing record, but I did not ger an error.

Thanks for all your hints.

**Comment by maharmstone** [comment]
> How to check there was an error during the execution?
> I do a test trying to update a non-existing record, but I did not ger an error.

Doing an UPDATE that affects zero rows isn't an error in SQL.
If you do something that causes an actual error (i.e. it would result in a message with red text in SSMS), it throws it as an exception, or calls the message handler if you have one set up. See the test program for an example.
