### ISSUE TITLE
Not issue - Question about Global for tds::tds çonn

### ISSUE THREAD

**Issue by devisbal** [maharmstone/tdscpp#7]
Hi:

Wil be possible to have the:

tds::tds çonn(server, username, password, "test program", "", show_msg);

A global for: conn?
This is for once the logging to the DB is done, do not have to logging again in other functions, and reuse the already one done.

BR

**Comment by maharmstone** [comment]
It's a variable like any other.

Please, give these things a try first before raising an issue.

**Comment by devisbal** [comment]
Hi:

If I do define it globally like:
tds::tds conn(db_server, db_user, db_password, "", db_database, show_msg);
And if the DB is down, it ends with a core dump.
Even the message that it's unable to connect to the IP:port shows up and when it rise the throw formatted_error
Since there is no way to use try/catch globally.
For your information: the globally is define outside main.
=
terminate called after throwing an instance of 'formatted_error'
  what():  Could not connect to 10.2.0.91:1433.
Aborted (core dumped)

tdscpp.cpp line 3370
        if (sock <= 0)
            throw formatted_error("Could not connect to {}:{}.", server, port);
BR

**Comment by maharmstone** [comment]
Stick in a std::unique_ptr then, and initialize it in main.
